import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.scss";
import {ThemeProvider} from "@/components/ThemeSelector/internal";

const manrope = Manrope({
  variable: "--font-manrope",
});

const involve = localFont({
    src: [
        {
            path: '../styles/involve/Involve-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../styles/involve/Involve-SemiBold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../styles/involve/Involve-Medium.ttf',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../styles/involve/Involve-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
    ],
    variable: "--font-involve",
})

export const metadata: Metadata = {
  title: "Alterix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${manrope.variable} ${involve.variable}`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
